### ISSUE TITLE
Text wrapping only affects new log messages

### ISSUE THREAD

**Issue by Seanm07** [JonathanDotCel/LessShittyLogcat#2]
The text wrap option should update all existing log messages, not just new log items.

![image](https://user-images.githubusercontent.com/17026918/92901490-6dfe5b80-f418-11ea-9da7-afeb3d85189a.png)

**Comment by JonathanDotCel** [comment]
Took a memory hit from this, but it'll now wrap previous strings.
It's not as CPU intensive as I'd worried though so it could be possible to just unwrap the string and re-wrap it in the future.
Cheers.
