### ISSUE TITLE
Some characters not accepted in filters

### ISSUE THREAD

**Issue by Seanm07** [JonathanDotCel/LessShittyLogcat#4]
Underscores, dashes and +/= are not accepted characters in filters even though all these characters can appear in logcat tags

![image](https://user-images.githubusercontent.com/17026918/92922609-0521de00-f42e-11ea-862f-a45caf504577.png)

![image](https://user-images.githubusercontent.com/17026918/92922759-3dc1b780-f42e-11ea-8ae4-23a02f96aa5e.png)

**Comment by JonathanDotCel** [comment]
Done, thanks.
You can now tab individually to the checkboxes and use +/- there... for some reason.
